import { LIT_NETWORK } from "@lit-protocol/constants";

export const DEFAULT_LIT_CONFIG = {
  network: LIT_NETWORK.DatilTest,
  debug: false,
};

export const SUPPORTED_CHAINS = [
  "ethereum",
  "polygon",
  "fantom",
  "xdai",
  "bsc",
  "arbitrum",
  "arbitrumSepolia",
  "avalanche",
  "fuji",
  "harmony",
  "mumbai",
  "goerli",
  "cronos",
  "optimism",
  "celo",
  "aurora",
  "eluvio",
  "alfajores",
  "xdc",
  "evmos",
  "evmosTestnet",
  "bscTestnet",
  "baseGoerli",
  "baseSepolia",
  "moonbeam",
  "moonriver",
  "moonbaseAlpha",
  "filecoin",
  "hyperspace",
  "sepolia",
  "scrollAlphaTestnet",
  "scroll",
  "zksync",
  "base",
  "lukso",
  "luksoTestnet",
  "zora",
  "zoraGoerli",
  "zksyncTestnet",
  "lineaGoerli",
  "lineaSepolia",
  "chronicleTestnet",
  "yellowstone",
  "lit",
  "chiado",
  "zkEvm",
  "mantleTestnet",
  "mantle",
  "klaytn",
  "publicGoodsNetwork",
  "optimismGoerli",
  "waevEclipseTestnet",
  "waevEclipseDevnet",
  "verifyTestnet",
  "fuse",
  "campNetwork",
  "vanar",
  "lisk",
  "chilizMainnet",
  "chilizTestnet",
  "skaleTestnet",
  "skale",
  "skaleCalypso",
  "fhenixHelium",
  "hederaTestnet",
  "bitTorrentTestnet",
  "storyIlaid",
  "campTestnet",
  "hushedNorthstar",
] as const;
